config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :posts
  root 'home#index'
  get 'posts/page/(:page(.:format))', to: 'posts#index'
  get '/home(/:hello)', to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :commentable, polymorphic: true
  validates :body, presence: true
  validates :body, length: { maximum: 1000, minimum: 1 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :commentators, through: :comments, source: :user

  validates :title, presence: true
  validates :title, length: { maximum: 120, minimum: 1 }
  validates :title, uniqueness: true
  validates :body, presence: true
  validates :body, length: { maximum: 3000, minimum: 1}
  validates :user, presence: true

  def find_moderators_posts
    #User.where(moderator: true).find_each { |u| p u.posts }
    Post.joins(:user).where(users: { moderator: true })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_destroy :log_before_destroy
  after_destroy :log_after_destroy

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commented_posts, through: :comments, source: :commentable, source_type: :Post
  has_many :commented_users, through: :comments, source: :commentable, source_type: :User

  validates :name, presence: true
  validates :name, length: { maximum: 16, minimum: 2 }
  validates :name, uniqueness: true

  private

  def log_before_destroy
    Rails.logger.info "##### Собираемся удалить пользователя #{name}. #####"
  end

  def log_after_destroy
    Rails.logger.info "##### Пользователь #{name} удалён. #####"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  prepend_view_path Rails.root.join('app/javascript')

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    Rails.logger.info '#######################################'
    Rails.logger.info params.inspect
    Rails.logger.info '#######################################'

    session[:times_here] ||= 0
    session[:times_here] += 1
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:user).page(params[:page]).per(3)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.page(params[:page]).per(3)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :visible)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :moderator, :creator, :banned, :comments_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
h1 Welcome to my RoR blog
p.alert.alert-primary  You have visited this page #{session[:times_here]} times.

= render "components/page/page" do
  p.alert.alert-success Hello from our first component!

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
  body
    = render 'shared/header'
    = yield

app/views/posts/_form.html.slim
= form_for post do |f|
  - if post.errors.any?
    #error_explanation
      h2 = "#{pluralize(post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :visible
    = f.check_box :visible
  .actions = f.submit

app/views/posts/_post.html.slim
tr
  td = post.title
  td = post.body
  td = post.user.name
  td = post.visible
  td = link_to 'Show', post
  td = link_to 'Edit', edit_post_path(post)
  td = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

app/views/posts/edit.html.slim
h1 Editing post

== render 'form', post: @post

=> link_to 'Show', @post
'|
=< link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts

table
  thead
    tr
      th Title
      th Body
      th User
      th Visible
      th
      th
      th

  tbody
    =render partial: 'post', collection: @posts

br
p
  = link_to 'New Post', new_post_path
p
  = paginate @posts

app/views/posts/new.html.slim
h1 New post

== render 'form', post: @post

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title
p
  strong Body:
  = @post.body
p
  strong User:
  = @post.user
p
  strong Visible:
  = @post.visible

p
  strong Comments:
  table
    - @comments.order(:created_at).each do |comment|
      tr
        td: b = comment.user.name
        td = comment.body

p
  = paginate @comments

=> link_to 'Edit', edit_post_path(@post)
'|
=< link_to 'Back', posts_path

app/views/shared/_header.html.slim
header
  navbar
    ul
      - if user_signed_in?
        li
          span t('label.hello') % current_user.name
        li
          = link_to t('label.logout'), destroy_user_session_path, method: :delete
      - else
        li
          = link_to t('label.login'), new_user_session_path
        li
          = link_to t('label.registration'), new_user_registration_path

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :moderator
    = f.check_box :moderator
  .field
    = f.label :creator
    = f.check_box :creator
  .field
    = f.label :banned
    = f.check_box :banned
  .field
    = f.label :comments_count
    = f.number_field :comments_count
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th Email
      th Moderator
      th Creator
      th Banned
      th Comments count
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = user.moderator
        td = user.creator
        td = user.banned
        td = user.comments_count
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Name: 
  = @user.name
p
  strong Email: 
  = @user.email
p
  strong Moderator: 
  = @user.moderator
p
  strong Creator: 
  = @user.creator
p
  strong Banned: 
  = @user.banned
p
  strong Comments count: 
  = @user.comments_count

- if @user.creator 
  p 
    strong Posts:
    table
      - @user.posts.order(:created_at).each do |post|
        tr
          td: b = post.title
          td = post.body

p
  strong Comments:
  table
    - @user.comments.order(:created_at).each do |comment|
      tr
        td = comment.body

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path